name: Build and Lint test

on:
  push:
  pull_request:
    branches:
      - master

jobs:

  lint-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2
    - run: npm i
    - run: npm run lint
    - run: npm run compile
